### ISSUE TITLE
v.1.3.0.0 not work on Mac

### ISSUE THREAD

**Issue by numanWD** [CRDS/Credits#10]
The Mac Wallet v.1.3.0.0 does not work in the 10.14.2 (18C54)

**Comment by razerrazer** [comment]
Is the Mac Wallet v.1.2.0.0 working for you on Mojave?

**Comment by numanWD** [comment]
Yes the `v.1.2.0.0` works on Mojave.

Do you need any report or trace log?

**Comment by thehalvo** [comment]
Same issue over here.

**Comment by andrewtookay** [comment]
I've looked at the code and I don't think there's anything there responsible for the wallet not working, I believe it might be just bad compiling and building.

**Comment by razerrazer** [comment]
since 1.3.0.1 is it working, so please close this case.

**Comment by mdrankin** [comment]
New patches for OSX will be included in v1.4.0.0.

@numanWD please re-test with the new version which will be released later today. Binaries may take another few days to be published, but should fix the issue.

Please open a new issue for v.1.4.0.0 if it's still not working as expected.
