### ISSUE TITLE
Build fails when "--disable-wallet" compile-time flag is used

### ISSUE THREAD

**Issue by gwestwood** [CRDS/Credits#21]
### Describe the issue
When trying to build with credit binaries without the wallet compiled in, it fails with an error.

### Steps to reproduce
1. Follow build steps, except replace ./configure with:
./configure --disable-wallet
2. make as usual.

### Expected behavior (tell us what should happen)
Build completes successfully.

### Actual behavior (tell us what happens instead)
Build fails with the error:

miner.cpp: In function ‘void CreditsMiner(const CChainParams&)’:
miner.cpp:570:89: error: too few arguments to function ‘std::unique_ptr<CBlockTemplate> CreateNewBlock(const CChainParams&, const CScript&)’
             pblocktemplate = std::unique_ptr<CBlockTemplate> (CreateNewBlock(chainparams));
                                                                                         ^
miner.cpp:202:33: note: declared here
 std::unique_ptr<CBlockTemplate> CreateNewBlock(const CChainParams& chainparams, const CScript& scriptPubKeyIn)
                                 ^
Makefile:5376: recipe for target 'libcredits_server_a-miner.o' failed

### What platform are you using (Linux, Windows, Mac)
Linux.

**Comment by andrewtookay** [comment]
I've looked into it right now and it is a pretty simple fix, it's most probably old code that right now has no use and it actually turned into a bug.

**Comment by andrewtookay** [comment]
Fixed in v1.3.1.0.
